name: "build-latest"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile"
      - "root/**"
      - copier.sh
      - meson-setup.sh
      - Makefile
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "Dockerfile"
      - copier.sh
      - meson-setup.sh
      - Makefile
      - isc-keyblock.asc

jobs:
  docker_buildx_debian:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        run: bash .github/version_extractor.sh Makefile >> $GITHUB_ENV

      - name: Build and push latest Debian image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: ./Dockerfile
          build-args:
            BIND_VERSION=${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}
          target: final
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jonasal/bind:latest
            jonasal/bind:${{ env.APP_MAJOR }}
            jonasal/bind:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}
            jonasal/bind:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}

  docker_buildx_alpine:
    runs-on: ubuntu-latest
    timeout-minutes: 100
    steps:
      - name: Perform setup steps
        uses: JonasAlfredsson/checkout-qemu-buildx@v2
        with:
          should_login: ${{ github.event_name != 'pull_request' }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        run: bash .github/version_extractor.sh Makefile >> $GITHUB_ENV

      - name: Build and push latest Alpine image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: ./Dockerfile
          build-args:
            BIND_VERSION=${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}
          target: final-alpine
          platforms: |
            linux/amd64
            linux/386
            linux/arm64
            linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            jonasal/bind:latest-alpine
            jonasal/bind:${{ env.APP_MAJOR }}-alpine
            jonasal/bind:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}-alpine
            jonasal/bind:${{ env.APP_MAJOR }}.${{ env.APP_MINOR }}.${{ env.APP_PATCH }}-alpine
